package festival.Interfaces;

import festival.Domain.Transaction;

/**
 * Created by Sebi on 26-Mar-17.
 */
public interface ITransactionRepository extends IRepository<Transaction, Integer> {
    /*
    Saves transaction and ignores given id
    (will be autogenerated)
     */
    void saveWithoutId(Transaction transaction);
}
